export const FETCH_USER = 'fetch_user'
export const FETCH_POSTS = 'get_posts'
export const ADD_POST = 'add_post'
export const SET_CURRENT_USER = 'set_current_user'
export const DELETE_POST = 'delete_post'
export const GET_ERRORS = 'get_errors'
export const GET_POST = 'get_post'
